import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/projects.index.tsx"),
  route("login", "routes/login.tsx"),
  route("logout", "routes/logout.tsx"),
  route("assistant", "routes/assistant.tsx"),
  route("marketplace", "routes/marketplace.tsx"),
  route("projects", "routes/projects.tsx"),
  route("resources", "routes/resources.tsx"),
  route("security", "routes/security.tsx"),
  route("services", "routes/services.tsx"),
  route("server", "routes/server.tsx", [
    route("runtimes", "routes/server.runtimes.tsx"),
    route("domains", "routes/server.domains.tsx"),
    route("access", "routes/server.access.tsx"),
    route("access/users", "routes/server.access.users.tsx"),
    route("access/permissions", "routes/server.access.permissions.tsx"),
    route("backups", "routes/server.backups.tsx"),
    route("logs", "routes/server.logs.tsx"),
    route("fabric", "routes/server.fabric.tsx", [
      route(":fabricSection", "routes/server.fabric.$fabricSection.tsx", [
        route(
          ":fabricDetail",
          "routes/server.fabric.$fabricSection.$fabricDetail.tsx",
        ),
      ]),
    ]),
  ]),
  route("settings", "routes/settings.tsx", [
    route("appearance", "routes/settings.appearance.tsx"),
  ]),
  route("projects/:projectId", "routes/index.tsx"),
  route("projects/:projectId/backend", "routes/backend.tsx"),
  route("projects/:projectId/extensions", "routes/extensions.tsx"),
  route("projects/:projectId/agents", "routes/agents.tsx"),
  route("projects/:projectId/auth", "routes/auth.tsx"),
  route("projects/:projectId/content", "routes/content.tsx", [
    route("new", "routes/content.new.tsx"),
    route(":contentType", "routes/content.$contentType.tsx", [
      index("routes/content.$contentType.index.tsx"),
      route("fields", "routes/content.$contentType.fields.tsx"),
      route(":entryId", "routes/content.$contentType.$entryId.tsx"),
    ]),
  ]),
  route("projects/:projectId/database", "routes/database.tsx"),
  route("projects/:projectId/database/new", "routes/database.new.tsx"),
  route("projects/:projectId/media", "routes/media.tsx"),
  route("projects/:projectId/marketplace", "routes/project.marketplace.tsx"),
  route("projects/:projectId/settings", "routes/project.settings.tsx"),
  route("projects/:projectId/storage", "routes/storage.tsx"),
  route("projects/:projectId/users", "routes/users.tsx"),
  route("projects/:projectId/frontend", "routes/frontend.tsx"),
  route("projects/:projectId/workloads", "routes/workloads.tsx"),
  route("projects/:projectId/workloads/functions", "routes/workloads.functions.tsx"),
  route("projects/:projectId/workloads/jobs", "routes/workloads.jobs.tsx"),
  route("projects/:projectId/workloads/schedules", "routes/workloads.schedules.tsx"),
  route("projects/:projectId/workloads/webhooks", "routes/workloads.webhooks.tsx"),
  route("projects/:projectId/workloads/new", "routes/workloads.new.tsx"),
  route("projects/:projectId/workloads/logs", "routes/workloads.logs.tsx"),
  route("projects/:projectId/workloads/settings", "routes/workloads.settings.tsx"),
  route("projects/:projectId/workloads/:workloadKind/:workloadId", "routes/workloads.$workloadId.tsx"),
  route("projects/:projectId/:managedSection", "routes/project.managed.$managedSection.tsx"),
  route("_api/relations/:collection", "routes/api.relations.$collection.tsx"),
  route("*", "routes/$.tsx"),
] satisfies RouteConfig;
