/**
 * The WordPress release this package installs, and the SHA-256 of its archive.
 *
 * Generated by `pnpm update:wordpress`; do not edit by hand. The digest is
 * pinned here, in the package that is frozen into each Project, so the download
 * is checked against something wordpress.org cannot change after the fact.
 */
export const WORDPRESS_RELEASE = "7.1.2";
export const WORDPRESS_ARCHIVE_SHA256 = "c0c666689d66b870d8825500bb8e402ed04de52602c61a6f516c6236b8c9ac67";
